### ISSUE TITLE
RiffRaff Deploys And CD For Frontend Cloudformation

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/front-pressed-lambda#44]
There are three components in this project that need to be deployed:

1. The `cmsFronts` cloudformation. This has both a RiffRaff deployment and CD set up as of #36.
2. The lambda code. This currently has a RiffRaff deployment configured but no CD.
3. The `frontend` cloudformation. This currently has no RiffRaff deployment set up and, therefore, no CD either.

```[tasklist]
### Tasks
- [x] Set up a RiffRaff deployment for the `frontend` cloudformation
- [x] Make the deployment for the `frontend` cloudformation a dependency of the lambda deployment
- [x] Set up CD for the lambda
```
